### ISSUE TITLE
My Wemos D1 Mini after is flashed the light flashes quickly and does spam some random chars on the terminal

### ISSUE THREAD

**Issue by tozeleal** [michaelshmitty/esperpass#10]
I sucessfuly flashed my Wemos D1 Mini but when i try to configure the SSID and other settings the terminal doesn't allow to insert any input 

For reference this where i got it: https://www.ebay.com/itm/D1-Mini-NodeMCU-Lua-ESP8266-ESP-12-WeMos-D1-Mini-WIFI-4M-Bytes-Module-NEW/272253589592?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

Putty settings:
http://prntscr.com/j0q2ar
http://prntscr.com/j0q2kk

Terminal:
http://prntscr.com/j0qnud

**Comment by michaelshmitty** [comment]
Thanks for trying it out and posting this well documented issue.

I believe I've encountered a similar issue at one point. It seems to have something to do with some initial data that gets written when they flash the Lua firmware in the factory. [Check out this section in Martin Ger's ESP WiFi Repeater README](https://github.com/martin-ger/esp_wifi_repeater#building-and-flashing). Scroll down to where it says "Sometimes, especially on old ESP-01s, there is a wrong or non-matching version of "esp_init_data_default.bin..." and follow the instructions.
Then reflash the ESPerPass firmware. Other users have reported success with this fix.

I must point out though that it seems like Nintendo has quietly shut down the StreetPass servers. These are the servers that kept track of all the StreetPass data your 3DS submits and receives when you get tagged. Without those servers StreetPass just no longer works. Using HomePass through means like ESPerPass and others will not solve that.
Check out #9 for links with more information.

**Comment by tozeleal** [comment]
Updated the problem... now i can't input anything on terminal

**Comment by michaelshmitty** [comment]
In your PuTTY screenshot settings I see "Implicit LF in every CR" switched off. Try switching that on and also fiddling with the Local echo options (Auto to Force etc.). Hope that helps!

**Comment by tozeleal** [comment]
Works! Thanks

**Comment by michaelshmitty** [comment]
You're welcome!
