### ISSUE TITLE
ESPerpass shuts wifi down for over 5min when the 3ds is in standby mode

### ISSUE THREAD

**Issue by tozeleal** [michaelshmitty/esperpass#12]
I don't know if someone noticed that

**Comment by michaelshmitty** [comment]
That's a feature, not a bug. To avoid malicious users to connect to the unprotected attwifi network and use your Internet connection the wemos switches on the wifi for only a few minutes and then shuts down for about 15 minutes. Then it randomly selects a new mac address and starts the cycle again. This gives a 3DS in standby enough time to get StreetPass hits but makes the unprotected WiFi network practically useless for others. See #7 for more on this.
